# Generated by Django 3.1.3 on 2020-12-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='restapi.position'),
            preserve_default=False,
        ),
    ]
