# Generated by Django 3.1.3 on 2020-12-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20201201_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='position',
        ),
        migrations.AddField(
            model_name='position',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='restapi.portfolio'),
            preserve_default=False,
        ),
    ]
